---
dependencies: []

galaxy_info:
  author: inrovo
  description: "Installs and configures Certbot (for Let's Encrypt)."
  company: "Inrovo"
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
        - 6
        - 7
    - name: Fedora
      versions:
        - all
    - name: Ubuntu
      versions:
        - all
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - certbot
    - letsencrypt
    - encryption
    - certificates
    - ssl
    - https
